//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neveinNadeen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMDb_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMDb_User()
        {
            this.Comments = new HashSet<Comment>();
            this.FavDirectors = new HashSet<FavDirector>();
            this.FavMovies = new HashSet<FavMovie>();
            this.FavActors = new HashSet<FavActor>();
            this.Rates = new HashSet<Rate>();
        }
    
        public int Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public int Role { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> FavMovie { get; set; }
        public Nullable<int> FavActor { get; set; }
        public Nullable<int> FavDirector { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavDirector> FavDirectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavMovie> FavMovies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavActor> FavActors { get; set; }
        public virtual Actor Actor { get; set; }
        public virtual Director Director { get; set; }
        public virtual Movie Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rates { get; set; }
    }
}
