//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neveinNadeen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMDb_Entities : DbContext
    {
        public IMDb_Entities()
            : base("name=IMDb_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<ActorMovie> ActorMovies { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<FavActor> FavActors { get; set; }
        public virtual DbSet<FavDirector> FavDirectors { get; set; }
        public virtual DbSet<FavMovie> FavMovies { get; set; }
        public virtual DbSet<IMDb_User> IMDb_User { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
    }
}
