//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neveinNadeen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int Id { get; set; }
        public Nullable<int> M_Id { get; set; }
        public Nullable<int> U_Id { get; set; }
        public Nullable<int> Like { get; set; }
        public Nullable<int> DisLike { get; set; }
    
        public virtual IMDb_User IMDb_User { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
